console.log('farto');
var myString;
var myNum;
var strArr;
// OR let strArr: Array<string>;
var numArr;
// OR let numArr: number[];
var strNumTuple;
myString = 'hello world';
myNum = 22;
strArr = ['A', 'B', 'D'];
numArr = [2, 3, 5, 7];
strNumTuple = ['Sean', 28];
console.log(myString, myNum);
console.log(strArr, numArr);
console.log(strNumTuple);
